// Curate the screen manifest:
//  1) Dedupe — keep ONE canonical screen per distinct title (the Stitch project
//     shipped many identical-titled duplicate screens; they read as "dead/repetitive").
//     Preference order for the canonical pick: a persona landing id, then DESKTOP,
//     then first occurrence.
//  2) Rename titles to the corrected person names (HTML bodies were already renamed;
//     the manifest titles still carried the old names -> nav/duplication mismatch).
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { PERSONAS } from '../src/data/personas.mjs';

const ROOT = 'C:/Users/hp/Desktop/KLM2026/ATUNSHE';
const raw = readFileSync(join(ROOT, 'src/data/screens.mjs'), 'utf8');
const jsonStart = raw.indexOf('export const screens =');
const manifest = JSON.parse(raw.slice(jsonStart + 'export const screens = '.length).replace(/;\s*$/, '').trim());

const landings = new Set(PERSONAS.map((p) => p.landing));

// 2) Title name fixes.
function fixTitle(t) {
  return t
    .replace('Clinical Encounter - Amina Okafor', 'Clinical Encounter - Adesenya')
    .replace('Patient Profile - Amina Okafor', 'Patient Profile - Juliet Okafor')
    .replace('Patient Timeline - Amina Okafor', 'Patient Timeline - Juliet Okafor')
    .replace('Staff Profile - Dr. Samuel Ojo', 'Staff Profile - Dr. Sola')
    .replace(/Amina Okafor/g, 'Adesenya')
    .replace(/Samuel Ojo/g, 'Sola');
}
manifest.forEach((s) => { s.title = fixTitle(s.title); });

// 1) Dedupe by (title) keeping canonical.
const rank = (s) => (landings.has(s.id) ? 0 : s.deviceType === 'DESKTOP' ? 1 : 2);
const byTitle = {};
for (const s of manifest) {
  const cur = byTitle[s.title];
  if (!cur) { byTitle[s.title] = s; continue; }
  if (rank(s) < rank(cur)) byTitle[s.title] = s; // prefer landing/desktop
}
const curated = Object.values(byTitle).sort((a, b) => a.group.localeCompare(b.group) || a.title.localeCompare(b.title));

// Drop the raw asset entry (logo png) from the interactive set; keep it only if referenced.
const interactive = curated.filter((s) => s.html && !s.asset);

writeFileSync(
  join(ROOT, 'src/data/screens.mjs'),
  '// AUTO-GENERATED by scripts/pull.mjs + scripts/curate.mjs\n' +
  '// De-duplicated verbatim Google Stitch screens (project 7855123187181213813).\n' +
  '// One canonical screen per distinct title; titles carry corrected person names.\n' +
  'export const screens = ' + JSON.stringify(interactive, null, 2) + ';\n'
);

console.log('Before:', manifest.length, '-> After dedupe:', interactive.length, 'screens.');
const g = {};
interactive.forEach((s) => (g[s.group] = (g[s.group] || 0) + 1));
console.log('By group:', JSON.stringify(g));
// sanity: landings preserved?
const missing = [...landings].filter((id) => !interactive.some((s) => s.id === id));
console.log('Missing landing ids:', missing.length ? missing : 'none');
