// Re-categorize existing screens (titles already known) + rewrite manifest with correct groups.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = 'C:/Users/hp/Desktop/KLM2026/ATUNSHE';
const raw = readFileSync(join(ROOT, 'src/data/screens.mjs'), 'utf8');
const jsonStart = raw.indexOf('export const screens =');
const jsonText = raw.slice(jsonStart + 'export const screens = '.length).replace(/;\s*$/, '').trim();
const manifest = JSON.parse(jsonText);

function categorize(title) {
  const t = (title || '').toLowerCase();
  if (t.endsWith('.png') || t.endsWith('.md')) return 'Assets & Docs';
  if (t.includes('login')) return 'Auth';
  if (t.includes('ogami')) return 'AI Assistant';
  if (t.includes('mobile')) return 'Mobile';
  if (t.includes('protocol')) return 'Protocols';
  if (t.includes('consent') || t.includes('chain of custody') || t.includes('trust & governance')) return 'Compliance & Ledgers';
  if (t.includes('billing') || t.includes('invoice') || t.includes('financial') || t.includes('revenue')) return 'Billing & Finance';
  if (t.includes('appointment') || t.includes('schedule') || t.includes('calendar') || t.includes('tasks')) return 'Scheduling';
  if (t.includes('administration') || t.includes('people') || t.includes('personnel') || t.includes('staff') || t.includes('institutions') || t.includes('configuration')) return 'Administration';
  if (t.includes('report') || t.includes('analytics') || t.includes('performance') || t.includes('migration') || t.includes('legacy') || t.includes('intelligence')) return 'Operations & Intelligence';
  if (t.includes('patient') || t.includes('directory') || t.includes('portal') || t.includes('profile') || t.includes('timeline') || t.includes('registration') || t.includes('encounter') || t.includes('vitals') || t.includes('record') || t.includes('consent')) return 'Clinical';
  if (t.includes('dashboard') || t.includes('home')) return 'Dashboards';
  return 'Clinical';
}

for (const s of manifest) {
  s.group = categorize(s.title);
}
manifest.sort((a, b) => a.group.localeCompare(b.group) || a.title.localeCompare(b.title));
writeFileSync(
  join(ROOT, 'src/data/screens.mjs'),
  '// AUTO-GENERATED by scripts/pull.mjs (groups recomputed by scripts/recategorize.mjs)\n' +
  '// 59 interactive screens + 1 logo asset. Verbatim Google Stitch screens, project 7855123187181213813.\n' +
  'export const screens = ' + JSON.stringify(manifest, null, 2) + ';\n'
);
const byGroup = {};
for (const s of manifest) byGroup[s.group] = (byGroup[s.group] || 0) + 1;
console.log('Groups:', JSON.stringify(byGroup, null, 0));
console.log('Total:', manifest.length);
